"""
Property-based tests for EnsemblePredictor.

**Validates: Requirements 3.1-3.12, 13.3-13.4**
**Properties: 13, 14, 15, 16**
"""

import pytest
from hypothesis import given, strategies as st, assume, settings
import numpy as np
import pandas as pd
from datetime import datetime
from typing import List

from stockiq.models.ensemble.predictor import (
    EnsemblePredictor,
    Prediction,
    predict_category
)


# Strategies for generating test data
@st.composite
def feature_dataframe(draw, n_features=10, min_samples=10, max_samples=100):
    """Generate a valid feature DataFrame for training/prediction."""
    n_samples = draw(st.integers(min_value=min_samples, max_value=max_samples))
    
    # Generate feature names
    feature_names = [f'feature_{i}' for i in range(n_features)]
    
    # Generate feature values - use reasonable ranges for financial data
    data = {}
    for feature in feature_names:
        # Generate column of floats
        values = draw(st.lists(
            st.floats(
                min_value=-10.0,
                max_value=10.0,
                allow_nan=False,
                allow_infinity=False
            ),
            min_size=n_samples,
            max_size=n_samples
        ))
        data[feature] = values
    
    return pd.DataFrame(data)


@st.composite
def target_series(draw, n_samples=None, min_value=-0.1, max_value=0.1):
    """Generate a valid target Series (returns)."""
    if n_samples is None:
        n_samples = draw(st.integers(min_value=10, max_value=100))
    
    values = draw(st.lists(
        st.floats(
            min_value=min_value,
            max_value=max_value,
            allow_nan=False,
            allow_infinity=False
        ),
        min_size=n_samples,
        max_size=n_samples
    ))
    
    return pd.Series(values, name='target_return')


@st.composite
def prediction_data(draw):
    """Generate valid Prediction object data."""
    ticker = draw(st.text(
        alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ",
        min_size=1,
        max_size=5
    ))
    
    # Generate a value
    value = draw(st.floats(
        min_value=-0.2,
        max_value=0.2,
        allow_nan=False,
        allow_infinity=False
    ))
    
    # Generate confidence in [0, 100]
    confidence = draw(st.floats(min_value=0.0, max_value=100.0))
    
    # Generate bounds with value in the middle
    margin = draw(st.floats(min_value=0.0, max_value=0.05))
    lower_bound = value - margin
    upper_bound = value + margin
    
    return {
        'ticker': ticker,
        'timestamp': datetime.now(),
        'prediction_type': 'return',
        'value': value,
        'confidence': confidence,
        'lower_bound': lower_bound,
        'upper_bound': upper_bound,
        'factors': {},
        'model': 'ensemble'
    }


class TestEnsemblePredictorProperties:
    """Property-based tests for EnsemblePredictor."""
    
    def setup_method(self):
        """Set up test fixtures."""
        # Mock cache to avoid Redis dependency
        import unittest.mock as mock
        self.mock_cache = mock.MagicMock()
        
    # Property 13: Confidence Range Validation
    @given(pred_data=prediction_data())
    @settings(max_examples=25, deadline=None)
    def test_property_13_confidence_in_range(self, pred_data):
        """
        **Validates: Requirements 3.3**
        
        Property 13: For any prediction generated by the ML_Engine,
        the confidence score SHALL be in the range [0, 100] inclusive.
        
        Formula: 0 ≤ confidence ≤ 100
        """
        # Create prediction with the data
        prediction = Prediction(**pred_data)
        
        # Property 13: Confidence must be in [0, 100]
        assert 0.0 <= prediction.confidence <= 100.0, (
            f"Property 13 violation: Confidence {prediction.confidence} not in [0, 100]"
        )
    
    # Property 13: Invalid confidence should raise error
    @given(
        pred_data=prediction_data(),
        invalid_confidence=st.floats(
            min_value=-1000.0,
            max_value=1000.0
        ).filter(lambda x: x < 0.0 or x > 100.0)
    )
    @settings(max_examples=15, deadline=None)
    def test_property_13_invalid_confidence_raises_error(self, pred_data, invalid_confidence):
        """
        **Validates: Requirements 3.3**
        
        Property 13 (negative test): Predictions with confidence outside
        [0, 100] SHALL raise ValueError.
        """
        pred_data['confidence'] = invalid_confidence
        
        with pytest.raises(ValueError, match="Property 13 violation"):
            Prediction(**pred_data)
    
    # Property 14: Category Assignment Consistency
    @given(pred_data=prediction_data())
    @settings(max_examples=25, deadline=None)
    def test_property_14_category_assignment(self, pred_data):
        """
        **Validates: Requirements 3.4**
        
        Property 14: For any prediction, the system SHALL assign exactly
        one category from the set {Strong Buy, Buy, Hold, Sell, Strong Sell}
        based on the prediction value and confidence.
        
        Category assignment rules:
        - Strong Buy: return > 5% AND confidence > 70%
        - Buy: return > 2%
        - Strong Sell: return < -5% AND confidence > 70%
        - Sell: return < -2%
        - Hold: otherwise
        """
        prediction = Prediction(**pred_data)
        
        # Property 14: Category must be assigned
        assert prediction.category is not None, (
            "Property 14 violation: Category not assigned"
        )
        
        # Category must be one of the valid categories
        valid_categories = {'Strong Buy', 'Buy', 'Hold', 'Sell', 'Strong Sell'}
        assert prediction.category in valid_categories, (
            f"Property 14 violation: Invalid category '{prediction.category}'"
        )
        
        # Verify category matches the assignment logic for return-based predictions
        return_pct = prediction.value * 100
        
        if return_pct > 5.0 and prediction.confidence > 70.0:
            assert prediction.category == 'Strong Buy', (
                f"Expected 'Strong Buy' for return={return_pct:.2f}%, conf={prediction.confidence:.1f}%"
            )
        elif return_pct > 2.0:
            assert prediction.category == 'Buy', (
                f"Expected 'Buy' for return={return_pct:.2f}%"
            )
        elif return_pct < -5.0 and prediction.confidence > 70.0:
            assert prediction.category == 'Strong Sell', (
                f"Expected 'Strong Sell' for return={return_pct:.2f}%, conf={prediction.confidence:.1f}%"
            )
        elif return_pct < -2.0:
            assert prediction.category == 'Sell', (
                f"Expected 'Sell' for return={return_pct:.2f}%"
            )
        else:
            assert prediction.category == 'Hold', (
                f"Expected 'Hold' for return={return_pct:.2f}%"
            )
    
    # Property 14: predict_category function consistency
    @given(pred_data=prediction_data())
    @settings(max_examples=15, deadline=None)
    def test_property_14_predict_category_function(self, pred_data):
        """
        **Validates: Requirements 3.4**
        
        Property 14: The predict_category() function SHALL return the same
        category as the one assigned to the Prediction object.
        """
        prediction = Prediction(**pred_data)
        
        # predict_category should return the same category
        category = predict_category(prediction)
        
        assert category == prediction.category, (
            f"predict_category() returned '{category}' but prediction.category is '{prediction.category}'"
        )
    
    # Property 15: Bounds Consistency
    @given(pred_data=prediction_data())
    @settings(max_examples=25, deadline=None)
    def test_property_15_bounds_consistency(self, pred_data):
        """
        **Validates: Requirements 3.5**
        
        Property 15: For any prediction with uncertainty bounds,
        the bounds SHALL satisfy the constraint:
        lower_bound ≤ predicted_value ≤ upper_bound
        """
        prediction = Prediction(**pred_data)
        
        # Property 15: Bounds consistency
        assert prediction.lower_bound <= prediction.value <= prediction.upper_bound, (
            f"Property 15 violation: Bounds inconsistent. "
            f"{prediction.lower_bound} ≤ {prediction.value} ≤ {prediction.upper_bound} is False"
        )
    
    # Property 15: Invalid bounds should raise error
    @given(pred_data=prediction_data())
    @settings(max_examples=15, deadline=None)
    def test_property_15_invalid_bounds_raises_error(self, pred_data):
        """
        **Validates: Requirements 3.5**
        
        Property 15 (negative test): Predictions with inconsistent bounds
        SHALL raise ValueError.
        """
        # Make bounds invalid (lower > value or upper < value)
        pred_data['lower_bound'] = pred_data['value'] + 1.0
        
        with pytest.raises(ValueError, match="Property 15 violation"):
            Prediction(**pred_data)
    
    # Property 16: Low Confidence Flagging
    @given(pred_data=prediction_data())
    @settings(max_examples=25, deadline=None)
    def test_property_16_low_confidence_flagging(self, pred_data):
        """
        **Validates: Requirements 3.12**
        
        Property 16: For any prediction, the low_confidence flag SHALL be
        set to True if and only if the confidence score is below 60%.
        
        Formula: low_confidence = True ⟺ confidence < 60.0
        """
        prediction = Prediction(**pred_data)
        
        # Property 16: Low confidence flagging
        expected_low_confidence = prediction.confidence < 60.0
        
        assert prediction.low_confidence == expected_low_confidence, (
            f"Property 16 violation: low_confidence flag is {prediction.low_confidence} "
            f"but should be {expected_low_confidence} (confidence={prediction.confidence})"
        )
    
    # Integration test: Train and predict with property validation
    @given(
        X_train=feature_dataframe(n_features=5, min_samples=30, max_samples=50)
    )
    @settings(max_examples=3, deadline=None)
    def test_ensemble_train_predict_properties(self, X_train):
        """
        **Validates: Requirements 3.1-3.12, 13.3-13.4**
        
        Integration test: Train an ensemble predictor and verify all properties
        hold for generated predictions.
        """
        # Generate target with same length as X_train
        y_train = pd.Series(
            np.random.randn(len(X_train)) * 0.02,
            name='target_return'
        )
        
        # Use first 5 rows for test
        X_test = X_train.head(5).copy()
        
        # Create predictor (no caching for tests)
        import unittest.mock as mock
        with mock.patch('stockiq.models.ensemble.predictor.get_cache'):
            predictor = EnsemblePredictor(
                n_estimators=10,  # Small for fast tests
                max_depth=3,
                cache_models=False
            )
            
            # Train
            predictor.train(X_train, y_train)
            
            # Predict
            predictions = predictor.predict(X_test)
            
            # Verify we got predictions for all samples
            assert len(predictions) == len(X_test), (
                f"Expected {len(X_test)} predictions, got {len(predictions)}"
            )
            
            # Verify all properties for each prediction
            for i, pred in enumerate(predictions):
                # Property 13: Confidence in [0, 100]
                assert 0.0 <= pred.confidence <= 100.0, (
                    f"Prediction {i}: Property 13 violation - confidence {pred.confidence} not in [0, 100]"
                )
                
                # Property 14: Valid category assigned
                valid_categories = {'Strong Buy', 'Buy', 'Hold', 'Sell', 'Strong Sell'}
                assert pred.category in valid_categories, (
                    f"Prediction {i}: Property 14 violation - invalid category '{pred.category}'"
                )
                
                # Property 15: Bounds consistency
                assert pred.lower_bound <= pred.value <= pred.upper_bound, (
                    f"Prediction {i}: Property 15 violation - bounds inconsistent "
                    f"({pred.lower_bound} ≤ {pred.value} ≤ {pred.upper_bound})"
                )
                
                # Property 16: Low confidence flagging
                expected_low_conf = pred.confidence < 60.0
                assert pred.low_confidence == expected_low_conf, (
                    f"Prediction {i}: Property 16 violation - low_confidence={pred.low_confidence} "
                    f"but should be {expected_low_conf} (confidence={pred.confidence})"
                )
    
    # Test feature importance extraction
    @given(X=feature_dataframe(n_features=5, min_samples=30, max_samples=50))
    @settings(max_examples=3, deadline=None)
    def test_feature_importance_extraction(self, X):
        """
        **Validates: Requirements 3.13**
        
        Test that feature importance can be extracted using SHAP
        and returns valid importance scores.
        """
        # Generate target with same length as X
        y = pd.Series(
            np.random.randn(len(X)) * 0.02,
            name='target_return'
        )
        
        # Create and train predictor
        import unittest.mock as mock
        with mock.patch('stockiq.models.ensemble.predictor.get_cache'):
            predictor = EnsemblePredictor(
                n_estimators=10,
                max_depth=3,
                cache_models=False
            )
            
            predictor.train(X, y)
            
            # Get feature importance
            importance = predictor.get_feature_importance()
            
            # Verify all features are present
            assert set(importance.keys()) == set(X.columns), (
                "Feature importance should include all features"
            )
            
            # Verify all importances are non-negative
            for feature, score in importance.items():
                assert score >= 0.0, (
                    f"Feature importance for '{feature}' should be non-negative, got {score}"
                )
            
            # Verify importances sum to approximately 1.0 (for RandomForest)
            # Edge case: if all features are constant (e.g., all zeros),
            # importances will all be 0.0 - this is expected behavior
            total_importance = sum(importance.values())
            if total_importance > 0:
                assert abs(total_importance - 1.0) < 0.01, (
                    f"Feature importances should sum to ~1.0, got {total_importance}"
                )
            else:
                # All features are constant, so all importances are 0
                # This is valid behavior
                pass


class TestPredictionDataclass:
    """Unit tests for Prediction dataclass validation."""
    
    def test_prediction_with_valid_data(self):
        """Test creating a prediction with valid data."""
        pred = Prediction(
            ticker='AAPL',
            timestamp=datetime.now(),
            prediction_type='return',
            value=0.06,  # 6% return
            confidence=75.0,
            lower_bound=0.04,
            upper_bound=0.08
        )
        
        assert pred.ticker == 'AAPL'
        assert pred.value == 0.06
        assert pred.confidence == 75.0
        assert pred.category == 'Strong Buy'  # 6% return with 75% confidence
        assert pred.low_confidence is False  # 75% > 60%
    
    def test_prediction_low_confidence(self):
        """Test low confidence flagging."""
        pred = Prediction(
            ticker='TSLA',
            timestamp=datetime.now(),
            prediction_type='return',
            value=0.03,
            confidence=55.0,
            lower_bound=0.01,
            upper_bound=0.05
        )
        
        assert pred.low_confidence is True  # 55% < 60%
        assert pred.category == 'Buy'  # 3% return
    
    def test_prediction_hold_category(self):
        """Test Hold category assignment."""
        pred = Prediction(
            ticker='MSFT',
            timestamp=datetime.now(),
            prediction_type='return',
            value=0.01,  # 1% return
            confidence=70.0,
            lower_bound=0.0,
            upper_bound=0.02
        )
        
        assert pred.category == 'Hold'  # Between -2% and 2%
    
    def test_prediction_sell_categories(self):
        """Test Sell and Strong Sell category assignment."""
        # Sell
        pred_sell = Prediction(
            ticker='XYZ',
            timestamp=datetime.now(),
            prediction_type='return',
            value=-0.03,  # -3% return
            confidence=50.0,
            lower_bound=-0.05,
            upper_bound=-0.01
        )
        assert pred_sell.category == 'Sell'
        
        # Strong Sell
        pred_strong_sell = Prediction(
            ticker='ABC',
            timestamp=datetime.now(),
            prediction_type='return',
            value=-0.07,  # -7% return
            confidence=80.0,
            lower_bound=-0.09,
            upper_bound=-0.05
        )
        assert pred_strong_sell.category == 'Strong Sell'


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
